=== mutilin/cpachecker-ldv/scripts/benchmark.dtd
<!ELEMENT benchmark ((rundefinition | option | propertyfile | sourcefiles | requiredfiles | resultfiles | require )*, columns?)>
<!ELEMENT rundefinition (sourcefiles | option | propertyfile)*>

<!ELEMENT sourcefiles (include | includesfile | exclude | option | propertyfile)*>
<!ELEMENT include (#PCDATA)>
<!ELEMENT includesfile (#PCDATA)>
<!ELEMENT exclude (#PCDATA)>
<!ELEMENT append (#PCDATA)>

<!ELEMENT requiredfiles (#PCDATA)>
<!ELEMENT resultfiles (#PCDATA)>
<!ELEMENT require>

<!ELEMENT option (#PCDATA)>
<!ELEMENT propertyfile (#PCDATA)>
<!ELEMENT columns (column*)>
<!ELEMENT column (#PCDATA)>

<!ATTLIST benchmark tool CDATA #REQUIRED>
<!ATTLIST benchmark memlimit CDATA #IMPLIED>
<!ATTLIST benchmark timelimit CDATA #IMPLIED>
<!ATTLIST benchmark hardtimelimit CDATA #IMPLIED>
<!ATTLIST benchmark cpuCores CDATA #IMPLIED>
<!ATTLIST benchmark threads CDATA #IMPLIED>

<!ATTLIST sourcefiles name CDATA #IMPLIED>

<!ATTLIST require cpuModel CDATA #IMPLIED>
<!ATTLIST require cpuCores CDATA "1">
<!ATTLIST require memory   CDATA "1">

<!ATTLIST test name CDATA #IMPLIED>
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST column title CDATA #IMPLIED
                 numberOfDigits CDATA #IMPLIED>

=== mutilin/cpachecker-ldv/test/assumptions/benchmark-predicate-heuristics.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" memlimit="14000">
  <test name="sbe-heuristic">
    <sourcefiles><include>test/programs/nondet_init_programs/systemc/transmitter.02.BUG.cil.c</include></sourcefiles>
    <option name="-setprop">output.disable=true</option>
    <option name="-config">test/config/symbpredabsCPA-sbe-heuristics.properties</option>
    <option name="-setprop">ProgressObserverCPA.cpa.assumptions.progressobserver.heuristics=RepetitionsInPathHeuristics</option>
    <option name="-setprop">RepetitionsInPathHeuristics.threshold=3</option>
    <option name="-heap">12000m</option>
  </test>
  <test name="sbe-heuristic">
    <sourcefiles><include>test/programs/nondet_init_programs/systemc/transmitter.03.BUG.cil.c</include></sourcefiles>
    <option name="-setprop">output.disable=true</option>
    <option name="-config">test/config/symbpredabsCPA-sbe-heuristics.properties</option>
    <option name="-setprop">ProgressObserverCPA.cpa.assumptions.progressobserver.heuristics=RepetitionsInPathHeuristics</option>
    <option name="-setprop">RepetitionsInPathHeuristics.threshold=4</option>
    <option name="-heap">12000m</option>
  </test>
  <test name="sbe">
    <sourcefiles>
      <include>test/programs/nondet_init_programs/systemc/transmitter.02.BUG.cil.c</include>
      <include>test/programs/nondet_init_programs/systemc/transmitter.03.BUG.cil.c</include>
    </sourcefiles>
    <option name="-setprop">output.disable=true</option>
    <option name="-config">test/config/symbpredabsCPA-sbe.properties</option>
    <option name="-heap">12000m</option>
  </test>
  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="reached">reached set</column>
    <column title="abstractions">Number of abstractions</column>
    <column title="refinements">Number of refinements</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/doc/examples/benchmark-cpachecker-release.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">

<benchmark tool="cpachecker" timelimit="900" memlimit="15000">

  <!-- GLOBAL OPTIONS -->
  <option name="-heap">12500m</option>
  <option name="-predicateAnalysis"/>
  <option name="-noout"/>

  <test name="concurrency"><sourcefiles>
      <includesfile>test/programs/benchmarks/Concurrency.set</includesfile>
  </sourcefiles></test>
  
  <test name="control"><sourcefiles>
      <includesfile>test/programs/benchmarks/ControlFlowInteger.set</includesfile>
  </sourcefiles></test>
  
  <test name="drivers"><sourcefiles>
      <includesfile>test/programs/benchmarks/DeviceDrivers.set</includesfile>
  </sourcefiles></test>
  
  <test name="drivers64">
      <sourcefiles>
          <includesfile>test/programs/benchmarks/DeviceDrivers64.set</includesfile>
      </sourcefiles>
      <option name="-setprop">cpa.predicate.machineModel=LINUX64</option>
  </test>
  
  <test name="heap"><sourcefiles>
      <includesfile>test/programs/benchmarks/HeapManipulation.set</includesfile>
  </sourcefiles></test>

  <test name="systemc"><sourcefiles>
      <includesfile>test/programs/benchmarks/SystemC.set</includesfile>
  </sourcefiles></test>

  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="reached">reached set</column>
    <column title="abstractions">Number of abstractions</column>
    <column title="refinements">Number of refinements</column>
    <column title="ref time">Time for refinements</column>
    <column title="cpa time">time for CPA algorithm</column>
  </columns>

</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/integration-mg.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">

<!--
     In the future, these integration tests are meant to test smgcpa as well as 
     smgcpa with explicitCPA without any kind of abstraction.
      -->
      
<benchmark tool="cpachecker" timelimit="60" hardtimelimit="90" memlimit="3000" cpuCores="2">

  <option name="-noout"/>
  <option name="-heap">2000M</option>
  <option name="-preprocess" />
  
  <propertyfile>${sourcefile_path}/ALL.prp</propertyfile>
    
  <rundefinition>
    
    <sourcefiles name ="label">
      <option name="-smg-label"/>
      <option name="-setprop">cpa.smg.handleUnknownFunctions=assume_safe</option>
      
      <include>../programs/smg_Explicity_Test/lists/*.c</include>
    </sourcefiles>
  
    <sourcefiles name="memsafety">
      <option name="-smg"/>
      <option name="-setprop">memorysafety.config=config/smg.properties</option>
      
      <include>../programs/smg_Explicity_Test/heap-memory/*.c</include>
    </sourcefiles>
  </rundefinition>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/VeriSec/Verisec_cbmc_bmc_pA_eA.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="10" memlimit="2000">
  <option name="-noout"/>
  <option name="-heap">1200m</option>

  <test name="bmc">
    <sourcefiles>
      <includesfile>test/test-sets/VeriSec/Verisec_cbmc_bmc_pA_eA-set.set</includesfile>
    </sourcefiles>
    <option name="-bmc"/>
  </test>
  
  <test name="cbmc">
    <sourcefiles>
      <includesfile>test/test-sets/VeriSec/Verisec_cbmc_bmc_pA_eA-set.set</includesfile>
    </sourcefiles>
    <option name="-cbmc"/>
  </test>
  
  <test name="-explicitAnalysis">
    <sourcefiles>
      <includesfile>test/test-sets/VeriSec/Verisec_cbmc_bmc_pA_eA-set.set</includesfile>
    </sourcefiles>
    <option name="-explicitAnalysis"/>
  </test>
  
<test name="-predicateAnalysis">
    <sourcefiles>
      <includesfile>test/test-sets/VeriSec/Verisec_cbmc_bmc_pA_eA-set.set</includesfile>
    </sourcefiles>
    <option name="-predicateAnalysis"/>
  </test>
  

  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="reached">reached set</column>
    <column title="memory">Heap memory usage</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/predicateAnalysis-lbe.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="1800" memlimit="2000">
  <test>
    <sourcefiles>
      <includesfile>test/test-sets/VeriSec.set</includesfile>
      <include>test/programs/linux-kernel/*.cil.c</include>
      <includesfile>test/programs/benchmarks/Concurrency.set</includesfile>
      <includesfile>test/programs/benchmarks/ControlFlowInteger.set</includesfile>
      <includesfile>test/programs/benchmarks/HeapManipulation.set</includesfile>
      <includesfile>test/programs/benchmarks/SystemC.set</includesfile>
      <includesfile>test/programs/benchmarks/DeviceDrivers.set</includesfile>
    </sourcefiles>
    <sourcefiles>
      <includesfile>test/programs/benchmarks/DeviceDrivers64.set</includesfile>
      <option name="-setprop">cpa.predicate.machineModel=Linux64</option>
    </sourcefiles>
    <option name="-noout"/>
    <option name="-predicateAnalysis-lbe"/>
    <option name="-heap">1200M</option>
  </test>
  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="reached">reached set</column>
    <column title="abstractions">Number of abstractions</column>
    <column title="refinements">Number of refinements</column>
    <column title="ref time">Time for refinements</column>
    <column title="cpa time">time for CPA algorithm</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/CPAAnalysis.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="300">
<option name="-heap">3000M</option>
<option name="-noout"/>
<option name="-disable-java-assertions"/>
<option name="-setprop">statistics.memory=false</option>

<rundefinition name="ReachDef_ExplicitDF">
	<option name="-reachingdef-explicit"/>
	<option name="-setprop">cpa.explicit.merge=JOIN</option>
		<sourcefiles name="BFS">
			<option name="-setprop">analysis.traversal.order=BFS</option>
			<include>test/programs/benchmarks/locks/test_locks_5_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_6_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_7_safe.c</include>
			<include>test/programs/benchmarks/bitvector/s3*_safe.BV.c.cil.c</include>
		</sourcefiles>
</rundefinition>

<rundefinition name="ReachDef_ExplicitJOINSEP">
	<option name="-reachingdef-explicit"/>
		<sourcefiles name="BFS">
			<option name="-setprop">analysis.traversal.order=BFS</option>
			<include>test/programs/benchmarks/locks/test_locks_5_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_6_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_7_safe.c</include>
			<include>test/programs/benchmarks/bitvector/s3*_safe.BV.c.cil.c</include>
		</sourcefiles>
</rundefinition>

<rundefinition name="ReachDef_ExplicitSEPJOIN">
	<option name="-reachingdef-explicit"/>
	<option name="-setprop">cpa.explicit.merge=JOIN</option>
	<option name="-setprop">cpa.reachdef.merge=SEP</option>
		<sourcefiles name="BFS">
			<option name="-setprop">analysis.traversal.order=BFS</option>
			<include>test/programs/benchmarks/locks/test_locks_5_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_6_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_7_safe.c</include>
			<include>test/programs/benchmarks/bitvector/s3*_safe.BV.c.cil.c</include>
		</sourcefiles>
</rundefinition>

<rundefinition name="ReachDef_ExplicitMC">
	<option name="-reachingdef-explicit"/>
	<option name="-setprop">cpa.reachdef.merge=SEP</option>
		<sourcefiles name="DFS">
			<option name="-setprop">analysis.traversal.order=DFS</option>
			<include>test/programs/benchmarks/locks/test_locks_5_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_6_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_7_safe.c</include>
			<include>test/programs/benchmarks/bitvector/s3*_safe.BV.c.cil.c</include>
		</sourcefiles>
</rundefinition>

<rundefinition name="ReachDefDF">
	<option name="-reachingdefinition"/>
		<sourcefiles name="BFS">
			<option name="-setprop">analysis.traversal.order=BFS</option>
			<include>test/programs/benchmarks/locks/test_locks_5_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_6_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_7_safe.c</include>
			<include>test/programs/benchmarks/bitvector/s3*_safe.BV.c.cil.c</include>
		</sourcefiles>
</rundefinition>

<rundefinition name="ExplicitDF">
	<option name="-explicit-trac-all"/>
	<option name="-setprop">cpa.explicit.merge=JOIN</option>
		<sourcefiles name="BFS">
			<option name="-setprop">analysis.traversal.order=BFS</option>
			<include>test/programs/benchmarks/locks/test_locks_5_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_6_safe.c</include>
			<include>test/programs/benchmarks/locks/test_locks_7_safe.c</include>
			<include>test/programs/benchmarks/bitvector/s3*_safe.BV.c.cil.c</include>
		</sourcefiles>
</rundefinition>

<rundefinition name="StructureTest">
	<option name="-reachingdef-explicit"/>
	<option name="-setprop">cpa.explicit.merge=JOIN</option>
		<sourcefiles name="BFS">
			<option name="-setprop">analysis.traversal.order=BFS</option>
			<include>test/programs/benchmarks/locks/test_locks_5_safe.c</include>
			<include>test/programs/nestedLocks/test_locks_while_seq_5_safe.c</include>
			<include>test/programs/nestedLocks/test_locks_while_mix_5_safe.c</include>
			<include>test/programs/nestedLocks/test_locks_while_nest_5_safe.c</include>
		</sourcefiles>
</rundefinition>

<columns>
<column title="Total time">Total time for CPAchecker</column>
<column title="Set up time">Time for analysis setup</column>
<column title="Analysis time">Time for Analysis</column>
<column title="Precision time">Time for precision adjustment</column>
<column title="Transfer time">Time for transfer relation</column>
<column title="Merge time">Time for merge operator</column>
<column title="Stop time">Time for stop operator</column>
<column title="#Removed Elems">Number of times merged</column>
</columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/predicateAnalysis_simple.bitvectors.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="120" memlimit="3000">

  <rundefinition>
    <!--<sourcefiles>
      <includesfile>integration-ControlFlowInteger.set</includesfile>
      <includesfile>../programs/benchmarks/FeatureChecks.set</includesfile>
      <includesfile>../programs/benchmarks/HeapManipulation.set</includesfile>
      <includesfile>../programs/benchmarks/Loops.set</includesfile>
      <includesfile>integration-SystemC.set</includesfile>
    </sourcefiles>-->
    <sourcefiles>
      <includesfile>../programs/simple/simple.set</includesfile>
      <option name="-32"/>
    </sourcefiles>
    <option name="-noout"/>
    <option name="-predicateAnalysis"/>
    <option name="-heap">2000M</option>
    <option name="-setprop">cpa.conditions.global.time.wall=1min</option>
    <option name="-setprop">cpa.predicate.solver=MATHSAT5</option>
    <option name="-setprop">cpa.predicate.ignoreCasts=false</option>
    <option name="-setprop">cpa.predicate.replaceBitvectorWithRationalAndFunctionTheory=false</option>
  </rundefinition>

  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="cpa time">time for CPA algorithm</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/explicit_interpolation.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" hardtimelimit="1020" memlimit="15000">
  <sourcefiles>
    <includesfile>../programs/benchmarks/ControlFlowInteger.set</includesfile>
    <includesfile>../programs/benchmarks/HeapManipulation.set</includesfile>
    <includesfile>../programs/benchmarks/Sequentialized.set</includesfile>
  </sourcefiles>

  <sourcefiles>
    <includesfile>../programs/benchmarks/DeviceDrivers64.set</includesfile>
    <option name="-64"/>
  </sourcefiles>

  <option name="-heap">12500M</option>
  <option name="-noout"></option>

  <propertyfile>../programs/benchmarks/PropertyERROR.prp</propertyfile>

  <rundefinition name="explicit-interpolation_scoped">
    <option name="-explicitAnalysis-ItpRefiner"/>
    <option name="-setprop">cpa.explicit.precision.refinement.useScopedInterpolation=true</option>
  </rundefinition>

  <rundefinition name="explicit-interpolation_unscoped">
    <option name="-explicitAnalysis-ItpRefiner"/>
    <option name="-setprop">cpa.explicit.precision.refinement.useScopedInterpolation=false</option>
  </rundefinition>


  <rundefinition name="explicit-interpolation_scoped_thres13">
    <option name="-explicitAnalysis-ItpRefiner"/>
    <option name="-setprop">CompositeCPA.cpas=cpa.location.LocationCPA,cpa.callstack.CallstackCPA,cpa.value.ValueAnalysisCPA,cpa.conditions.global.GlobalConditionsCPA,cpa.conditions.path.PathConditionsCPA</option>
    <option name="-setprop">cpa.conditions.path.condition=AssignmentsInPathCondition</option>
    <option name="-setprop">cpa.explicit.precision.path.defaultThreshold=13</option>
    <option name="-setprop">cpa.explicit.precision.refinement.useScopedInterpolation=true</option>
  </rundefinition>

  <rundefinition name="explicit-interpolation_unscoped_thres13">
    <option name="-explicitAnalysis-ItpRefiner"/>
    <option name="-setprop">CompositeCPA.cpas=cpa.location.LocationCPA,cpa.callstack.CallstackCPA,cpa.value.ValueAnalysisCPA,cpa.conditions.global.GlobalConditionsCPA,cpa.conditions.path.PathConditionsCPA</option>
    <option name="-setprop">cpa.conditions.path.condition=AssignmentsInPathCondition</option>
    <option name="-setprop">cpa.explicit.precision.path.defaultThreshold=13</option>
    <option name="-setprop">cpa.explicit.precision.refinement.useScopedInterpolation=false</option>
  </rundefinition>


  <rundefinition name="explicit-interpolation_scoped_thres13_abelf">
    <option name="-explicitAnalysis-ItpRefiner-ABElf"/>
    <option name="-setprop">CompositeCPA.cpas=cpa.location.LocationCPA,cpa.callstack.CallstackCPA,cpa.value.ValueAnalysisCPA,cpa.predicate.PredicateCPA,cpa.conditions.global.GlobalConditionsCPA,cpa.conditions.path.PathConditionsCPA</option>    
    <option name="-setprop">cpa.conditions.path.condition=AssignmentsInPathCondition</option>
    <option name="-setprop">cpa.explicit.precision.path.defaultThreshold=13</option>
    <option name="-setprop">cpa.explicit.precision.refinement.useScopedInterpolation=true</option>
  </rundefinition>

  <columns>
    <column title="#refs">Number of refinements:</column>
    <column title="#expRefs">number of explicit-interpolation-based refinements:</column>
    <column title="#intpols">number of explicit-interpolations:</column>
    <column title="#elemsInErrPath">total number of elements in error paths:</column>
    <column title="elemsChecked">percentage of elements checked:</column>
    <column title="maxTimeSingleIntpol">max. time for singe interpolation:</column>
    <column title="totalTimeIntpol">total time for interpolation:</column>
  </columns>
</benchmark>
