=== mutilin/cpachecker-ldv/scripts/benchmark.dtd
<!ELEMENT benchmark ((rundefinition | option | propertyfile | sourcefiles | requiredfiles | resultfiles | require )*, columns?)>
<!ELEMENT rundefinition (sourcefiles | option | propertyfile)*>

<!ELEMENT sourcefiles (include | includesfile | exclude | option | propertyfile)*>
<!ELEMENT include (#PCDATA)>
<!ELEMENT includesfile (#PCDATA)>
<!ELEMENT exclude (#PCDATA)>
<!ELEMENT append (#PCDATA)>

<!ELEMENT requiredfiles (#PCDATA)>
<!ELEMENT resultfiles (#PCDATA)>
<!ELEMENT require>

<!ELEMENT option (#PCDATA)>
<!ELEMENT propertyfile (#PCDATA)>
<!ELEMENT columns (column*)>
<!ELEMENT column (#PCDATA)>

<!ATTLIST benchmark tool CDATA #REQUIRED>
<!ATTLIST benchmark memlimit CDATA #IMPLIED>
<!ATTLIST benchmark timelimit CDATA #IMPLIED>
<!ATTLIST benchmark hardtimelimit CDATA #IMPLIED>
<!ATTLIST benchmark cpuCores CDATA #IMPLIED>
<!ATTLIST benchmark threads CDATA #IMPLIED>

<!ATTLIST sourcefiles name CDATA #IMPLIED>

<!ATTLIST require cpuModel CDATA #IMPLIED>
<!ATTLIST require cpuCores CDATA "1">
<!ATTLIST require memory   CDATA "1">

<!ATTLIST test name CDATA #IMPLIED>
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST column title CDATA #IMPLIED
                 numberOfDigits CDATA #IMPLIED>

=== mutilin/cpachecker-ldv/doc/examples/benchmark.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<!-- Example file that demonstrates all available options. -->

<!--
  "tool" is the tool to verify.
  All tools for which a corresponding module in scripts/benchmark/tool exists are supported.
  Examples are "cbmc" and "cpachecker".

  "timelimit" is an optional cpu-time limit in seconds.
  "hardtimelimit" is an optional cpu-time limit after which the tool will be killed forcefully
    equal to "timelimit" if not specified).
  "memlimit" is an optional memory limit in megabytes.
  "cpuCores" is an optional number of CPU cores to use per run (otherwise all available cores are used).
  "threads" is the number of parallel executions of verification runs.
  This values can be overriden on the command line when running benchmark.py
-->
<benchmark tool="cbmc" timelimit="1800" hardtimelimit="2000" memlimit="200">

  <!--
    There are two important top-level tags:
    <rundefinition>
    <sourcefiles>

    A <rundefinition> tag defines a set of runs of the tool which will be executed
    for all files mentioned in all <sourcefiles> tags.
    Both tags may appear arbitrarily often and
    support an optional attribute "name" in order to distinguish them.

    Inside a <sourcefiles> tag, the tags <include>, <exclude>, and <includesfile>
    may appear. All take a file name (supporting wildcards, variables, etc.) as content.
    <include> and <exclude> may be used to include or exclude files for verification runs directly.
    <includesfile> needs to reference text files which may contain
    further file name patterns (each pattern on one line) of files that will be used for verification.
    All relative paths specified here are relative to the directory of this file.
    Relative paths specified inside a file referenced with <includesfile>
    are relative to the directory of that file.

    Another tag is <option> which defines a command-line argument
    for the verification tool.
    This tag may appear as a top-level tag, inside <rundefinition> tags,
    and inside <sourcefiles> tags, and the argument is used for all files,
    only in the specific set of runs, or only for the specific set of files,
    respectively.
    The tag has a required attribute "name" and optionally takes some text content.

    Both the file name patterns as well as the values of options
    may contain variables in a "${VAR}" syntax that will be replaced by the script.
    This list of allowed variables is:
    benchmark_name
    benchmark_date
    benchmark_path
    benchmark_path_abs
    benchmark_file
    benchmark_file_abs
    rundefinition_name
    logfile_path
    logfile_path_abs
    sourcefile_name
    sourcefile_path
    sourcefile_path_abs
    C.f. benchmark-cpachecker.xml for an example of variable usage.

    Furthermore, a <columns> tag may appear as a top-level tag
    with a list of <column> tags inside. The script will then try to find values
    for the specified columns in the output of the verification tool.
    This is currently only supported for CPAchecker
    and not guaranteed to be supported in the future at all.
    C.f. benchmark-cpachecker.xml for an example.

    There are three more top-level tags that are used only when the verifier cloud is used:

    <requiredfiles> can be used to specify additional files that are needed
    for executing the benchmark. The tag may contain a path to a file or directory
    that is transmitted to the worker. Wildcards, environment variables etc. are resolved.
    The tag may appear several times.

    <require> can be used to select a specific set of worker machines. The attributes
    "cpuModel" (giving a string that needs to be contained in the worker's CPU name),
    "cpuCores" (giving the minimal number of CPU cores), and
    "memory" (giving the minimal amount of memory in MB) can be specified (all optional).
    The tag may appear several times, but each attribute may appear at most once
    (so you can specify all attributes in a single tag or spread over several occurrences).

    <resultfiles> can be used to specify a file-name pattern matching all the result
    files created by the tool that should be transported back after executing the run
    from the worker to the user's machine.
  -->

  <!-- Example: -->

  <!-- Define some global options. -->
  <option name="--error-label">ERROR</option>

  <!-- Define a set of sourcefiles that will be used with all run definitions. -->
  <sourcefiles name="small_locks">
    <include>../../test/programs/benchmarks/locks/*.c</include>
    <exclude>../../test/programs/benchmarks/locks/test_locks_1?*.c</exclude>
  </sourcefiles>

  <!-- Define a run definition with one specific option. -->
  <rundefinition name="small_locks">
    <option name="--unwind">10</option>
  </rundefinition>

  <!-- Define another run definition with one other specific option and some more files. -->
  <rundefinition name="all_locks">
    <option name="--unwind">1</option>

    <sourcefiles name="big_locks">
      <include>../../test/programs/benchmarks/locks/test_locks_1?*.c</include>
    </sourcefiles>
  </rundefinition>

  <!-- Yet another run definition, this time using an <includesfile>
       and a command-line option which is specific for some files. -->
  <rundefinition name="locks+drivers">
    <option name="--unwind">1</option>

    <sourcefiles name="drivers">
      <includesfile>../../test/programs/benchmarks/DeviceDrivers64.set</includesfile>
      <option name="--64"/>
    </sourcefiles>
  </rundefinition>

  <!-- Some requirements for the worker machine. -->
  <require memory="512" cpuCores="2"/>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/sv-comp14.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" memlimit="15000" cpuCores="4">
  <option name="-disable-java-assertions"/>
  <option name="-heap">10000M</option>

  <propertyfile>${sourcefile_path}/ALL.prp</propertyfile>

  <sourcefiles name="Simple">
    <includesfile>../programs/benchmarks/Simple.set</includesfile>
  </sourcefiles>
  <sourcefiles name="BitVectors">
    <includesfile>../programs/benchmarks/BitVectors.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Concurrency">
    <includesfile>../programs/benchmarks/Concurrency.set</includesfile>
  </sourcefiles>
  <sourcefiles name="ControlFlowInteger">
    <includesfile>../programs/benchmarks/ControlFlowInteger.set</includesfile>
  </sourcefiles>
  <sourcefiles name="DeviceDrivers64">
    <includesfile>../programs/benchmarks/DeviceDrivers64.set</includesfile>
    <option name="-64"/>
  </sourcefiles>
  <!-- Demonstration Category
  <sourcefiles name="DriverChallenges">
    <includesfile>../programs/benchmarks/DriverChallenges.set</includesfile>
    <option name="-64"/>
  </sourcefiles>
  -->
  <sourcefiles name="HeapManipulation">
    <includesfile>../programs/benchmarks/HeapManipulation.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Loops">
    <includesfile>../programs/benchmarks/Loops.set</includesfile>
  </sourcefiles>
  <sourcefiles name="MemorySafety">
    <includesfile>../programs/benchmarks/MemorySafety.set</includesfile>
  </sourcefiles>
  <sourcefiles name="ProductLines">
    <includesfile>../programs/benchmarks/ProductLines.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Recursive">
    <includesfile>../programs/benchmarks/Recursive.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Sequentialized">
    <includesfile>../programs/benchmarks/Sequentialized.set</includesfile>
  </sourcefiles>

  <rundefinition name="sv-comp14">
    <option name="-sv-comp14"/>
  </rundefinition>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/predicateAnalysis_bitvectors.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="240" memlimit="5000">

  <rundefinition>
    <sourcefiles>
      <includesfile>../programs/benchmarks/BitVectors.set</includesfile>
      <option name="-32"/>
    </sourcefiles>
    <option name="-noout"/>
    <option name="-spec">sv-comp</option>
    <option name="-predicateAnalysis"/>
    <option name="-heap">2500M</option>
    <option name="-setprop">limits.time.cpu=3min</option>
    <option name="-setprop">cpa.predicate.solver=MATHSAT5</option>
    <option name="-setprop">cpa.predicate.ignoreCasts=false</option>
    <option name="-setprop">cpa.predicate.replaceBitvectorWithRationalAndFunctionTheory=false</option>
  </rundefinition>

  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="cpa time">time for CPA algorithm</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/assumptions/benchmark-uninitvars-adjustable-conditions.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="180" memlimit="14000">
  <option name="-noout"/>
  <option name="-heap">12000m</option>

  <test name="uninitvars">
    <sourcefiles>
      <includesfile>test/assumptions/adjustableConditions-uninitvars.set</includesfile>
    </sourcefiles>
    <option name="-uninitVars-heuristics"/>
  </test>
  <test name="uninitvars-pl">
    <sourcefiles>
      <includesfile>test/assumptions/adjustableConditions-uninitvars.set</includesfile>
    </sourcefiles>
    <option name="-config">test/assumptions/uninitvars-adjustableConditions.properties</option>
    <option name="-setprop">cpa.assumptions.progressobserver.heuristics=PathLengthHeuristics,TimeOutHeuristics</option>
  </test>
  <test name="uninitvars-rip">
    <sourcefiles>
      <includesfile>test/assumptions/adjustableConditions-uninitvars.set</includesfile>
    </sourcefiles>
    <option name="-config">test/assumptions/uninitvars-adjustableConditions.properties</option>
    <option name="-setprop">cpa.assumptions.progressobserver.heuristics=RepetitionsInPathHeuristics,TimeOutHeuristics</option>
  </test>
  <test name="uninitvars-ae">
    <sourcefiles>
      <includesfile>test/assumptions/adjustableConditions-uninitvars.set</includesfile>
    </sourcefiles>
    <option name="-config">test/assumptions/uninitvars-adjustableConditions.properties</option>
    <option name="-setprop">cpa.assumptions.progressobserver.heuristics=AssumeEdgesInPathHeuristics,TimeOutHeuristics</option>
  </test>
  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="uninit">No of uninitialized vars</column>
    <column title="threshold">Threshold value</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/integration-octagonAnalysis.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="60" hardtimelimit="90" memlimit="3000" cpuCores="2">

  <option name="-noout"/>
  <option name="-octagonAnalysis-refiner"/>

  <propertyfile>${sourcefile_path}/ALL.prp</propertyfile>

  <rundefinition>
	<!-- Integer Tests -->
	<sourcefiles name="ControlFlowInteger">
		<option name="-setprop">cpa.octagon.handleFloats=false</option>
        	<option name="-setprop">cpa.octagon.octagonLibrary=INT</option>
        	<include>../programs/benchmarks/ntdrivers-simplified/*_false-unreach-call*.cil.c</include>
        	<include>../programs/benchmarks/ntdrivers-simplified/*_true-unreach-call*.cil.c</include>
        	<include>../programs/benchmarks/ssh-simplified/*_false-unreach-call*.cil.c</include>
        	<include>../programs/benchmarks/ssh-simplified/*_true-unreach-call*.cil.c</include>
        	<include>../programs/benchmarks/locks/*_false-unreach-call*.c</include>
        	<include>../programs/benchmarks/locks/*_true-unreach-call*.c</include>
        	<include>../programs/benchmarks/eca/Problem0*_false-unreach-call*.c</include>
        	<include>../programs/benchmarks/eca/Problem0*_true-unreach-call*.c</include>
                <exclude>../programs/benchmarks/eca/Problem03*.c</exclude>
		<exclude>../programs/benchmarks/eca/Problem04*.c</exclude>
                <exclude>../programs/benchmarks/eca/Problem06*.c</exclude>
                <exclude>../programs/benchmarks/eca/Problem07*.c</exclude>
                <exclude>../programs/benchmarks/eca/Problem08*.c</exclude>
                <exclude>../programs/benchmarks/eca/Problem09*.c</exclude>
      	</sourcefiles>
  	<sourcefiles name="Sequentialized">
		<option name="-setprop">cpa.octagon.handleFloats=false</option>
        	<option name="-setprop">cpa.octagon.octagonLibrary=INT</option>
    		<include>../programs/benchmarks/systemc/*_false-unreach-call*.cil.c</include>
    		<include>../programs/benchmarks/systemc/*_true-unreach-call*.cil.c</include>
  	</sourcefiles>	
    	<sourcefiles name="OctagonRegression-int">
		<option name="-setprop">cpa.octagon.handleFloats=false</option>
        	<option name="-setprop">cpa.octagon.octagonLibrary=INT</option>
      		<includesfile>../programs/simple/octagon/octagon-int.set</includesfile>
    	</sourcefiles>
  	<sourcefiles>
		<option name="-setprop">cpa.octagon.handleFloats=false</option>
        	<option name="-setprop">cpa.octagon.octagonLibrary=INT</option>
		<includesfile>integration-DeviceDrivers64.set</includesfile>
      		<option name="-64"/>
    	</sourcefiles>

	<!-- Widening Tests -->
        <sourcefiles name="Loops">
		<option name="-setprop">cpa.octagon.handleFloats=false</option>
        	<option name="-setprop">cpa.octagon.octagonLibrary=INT</option>
		<includesfile>../programs/benchmarks/Loops.set</includesfile>
		<option name="-setprop">analysis.algorithm.CEGAR=false</option>
		<option name="-setprop">cpa.octagon.initialPrecisionType=STATIC_FULL</option>
		<option name="-setprop">analysis.checkCounterexamples=true</option>
		<option name="-setprop">counterexample.checker=CPACHECKER</option>
		<option name="-setprop">counterexample.checker.config=config/octagonAnalysis.properties</option>
	</sourcefiles>   
 
        <!-- Float Tests -->
        <sourcefiles name="OctagonRegression-float">
                <includesfile>../programs/simple/octagon/octagon-float.set</includesfile>
                <option name="-setprop">cpa.octagon.handleFloats=true</option>
                <option name="-setprop">cpa.octagon.octagonLibrary=FLOAT</option>
        </sourcefiles>

     </rundefinition>

  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="reached">reached set</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/doc/examples/benchmark-safe.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="safe" timelimit="10" memlimit="10">

<!--This file demonstrates the use of a tool named "safe",
    that returns SAFE for every input.

    After running this file, you will get many resultfiles in XML-format,
    one for each run definition and one for each sourcefiles-block per run definition.
    This allows to create several different tables.
    2 tests and 6 blocks result in 14 resultfiles. -->

    <sourcefiles name="concurrency">
        <includesfile>../../test/programs/benchmarks/Concurrency.set</includesfile>
    </sourcefiles>
    
    <sourcefiles name="control">
        <includesfile>../../test/programs/benchmarks/ControlFlowInteger*.set</includesfile>
    </sourcefiles>
    
    <sourcefiles name="heap">
        <includesfile>../../test/programs/benchmarks/HeapManipulation.set</includesfile>
    </sourcefiles>
    
    <sourcefiles name="systemc">
        <includesfile>../../test/programs/benchmarks/SystemC.set</includesfile>
    </sourcefiles>
    
    <sourcefiles name="drivers64">
        <includesfile>../../test/programs/benchmarks/DeviceDrivers64.set</includesfile>
    </sourcefiles>

    <rundefinition name="firstTest">
        <option name="-optionX">unused</option>
    </rundefinition>
    
    <rundefinition name="anotherTest">
        <option name="-optionY">unused</option>
    </rundefinition>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/cpalien.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900">
  <option name="-disable-java-assertions"/>
  <option name="-heap">12000M</option>
  <option name="-preprocess" />

  <sourcefiles name="cpalien">
    <includesfile>../programs/cpalien/cpalien.set</includesfile>
  </sourcefiles>

  <rundefinition name="cpalien">
    <option name="-CPAlien"/>
  </rundefinition>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/induction.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" hardtimelimit="1000" memlimit="15000" cpuCores="2">
  <option name="-heap">13000M</option>
  <option name="-noout"/>
  <option name="-disable-java-assertions"/>

  <propertyfile>${sourcefile_path}/ALL.prp</propertyfile>

  <sourcefiles name="ControlFlowInteger">
    <includesfile>../programs/benchmarks/ControlFlowInteger.set</includesfile>
  </sourcefiles>
  <sourcefiles name="DeviceDrivers64">
    <includesfile>../programs/benchmarks/DeviceDrivers64.set</includesfile>
    <option name="-setprop">cpa.predicate.handlePointerAliasing=false</option>
    <option name="-64"/>
  </sourcefiles>
  <sourcefiles name="ECA">
    <includesfile>../programs/benchmarks/ECA.set</includesfile>
  </sourcefiles>
  <sourcefiles name="HeapManipulation">
    <includesfile>../programs/benchmarks/HeapManipulation.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Loops">
    <includesfile>../programs/benchmarks/Loops.set</includesfile>
  </sourcefiles>
  <sourcefiles name="ProductLines">
    <includesfile>../programs/benchmarks/ProductLines.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Sequentialized">
    <includesfile>../programs/benchmarks/Sequentialized.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Simple">
    <includesfile>../programs/benchmarks/Simple.set</includesfile>
    <option name="-setprop">cpa.predicate.handlePointerAliasing=false</option>
  </sourcefiles>

  <rundefinition>
    <option name="-bmc-induction"/>
    <!-- TODO: use these options?
    <option name="-setprop">cfa.useMultiEdges=true</option>
    <option name="-setprop">bmc.addInvariantsByInduction=false</option>
    -->
  </rundefinition>

  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="cut points">cut points for induction</column>
    <column title="formula creation">Time for induction formula creation</column>
    <column title="induction check">Time for induction check</column>
    <column title="invariant creation">Time for invariant generation</column>
  </columns>
</benchmark>
