=== mutilin/cpachecker-ldv/scripts/benchmark.dtd
<!ELEMENT benchmark ((rundefinition | option | propertyfile | sourcefiles | requiredfiles | resultfiles | require )*, columns?)>
<!ELEMENT rundefinition (sourcefiles | option | propertyfile)*>

<!ELEMENT sourcefiles (include | includesfile | exclude | option | propertyfile)*>
<!ELEMENT include (#PCDATA)>
<!ELEMENT includesfile (#PCDATA)>
<!ELEMENT exclude (#PCDATA)>
<!ELEMENT append (#PCDATA)>

<!ELEMENT requiredfiles (#PCDATA)>
<!ELEMENT resultfiles (#PCDATA)>
<!ELEMENT require>

<!ELEMENT option (#PCDATA)>
<!ELEMENT propertyfile (#PCDATA)>
<!ELEMENT columns (column*)>
<!ELEMENT column (#PCDATA)>

<!ATTLIST benchmark tool CDATA #REQUIRED>
<!ATTLIST benchmark memlimit CDATA #IMPLIED>
<!ATTLIST benchmark timelimit CDATA #IMPLIED>
<!ATTLIST benchmark hardtimelimit CDATA #IMPLIED>
<!ATTLIST benchmark cpuCores CDATA #IMPLIED>
<!ATTLIST benchmark threads CDATA #IMPLIED>

<!ATTLIST sourcefiles name CDATA #IMPLIED>

<!ATTLIST require cpuModel CDATA #IMPLIED>
<!ATTLIST require cpuCores CDATA "1">
<!ATTLIST require memory   CDATA "1">

<!ATTLIST test name CDATA #IMPLIED>
<!ATTLIST option name CDATA #REQUIRED>
<!ATTLIST column title CDATA #IMPLIED
                 numberOfDigits CDATA #IMPLIED>

=== mutilin/cpachecker-ldv/test/test-sets/sv-comp-abm.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" memlimit="15000">

  <test name="predicateAnalysis-abm">
    <sourcefiles>
      <includesfile>test/programs/benchmarks/Concurrency.set</includesfile>
      <includesfile>test/programs/benchmarks/ControlFlowInteger.set</includesfile>
      <includesfile>test/programs/benchmarks/HeapManipulation.set</includesfile>
      <includesfile>test/programs/benchmarks/SystemC.set</includesfile>
      <option name="-sv-comp12-abm"/>
    </sourcefiles>
    <sourcefiles>
      <includesfile>test/programs/benchmarks/DeviceDrivers.set</includesfile>
      <option name="-sv-comp12-abm-funpoint"/>
    </sourcefiles>
    <sourcefiles>
      <includesfile>test/programs/benchmarks/DeviceDrivers64.set</includesfile>
      <option name="-setprop">cpa.predicate.machineModel=Linux64</option>
      <option name="-sv-comp12-abm"/>
    </sourcefiles>    
    <option name="-heap">12500m</option>
  </test>

  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="cpa time">time for CPA algorithm</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/assumptions/benchmark-cbmc-10.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cbmc" timelimit="900" memlimit="12000">
  <test>
    <sourcefiles>test/programs/*-simplified/*.cil.c</sourcefiles>
    <sourcefiles>test/programs/systemc/[bk]*.cil.c</sourcefiles>
    <sourcefiles>test/programs/systemc/mem_slave_tlm.1.cil.c</sourcefiles>
    <sourcefiles>test/programs/systemc/pc_sfifo_?.cil.c</sourcefiles>
    <sourcefiles>test/programs/systemc/token_ring.0[12].cil.c</sourcefiles>
    <sourcefiles>test/programs/systemc/toy?_BUG.cil.c</sourcefiles>
    <sourcefiles>test/programs/systemc/transmitter*.cil.c</sourcefiles>
    <options>
      <option name="--32"/>
      <option name="--error-label">ERROR</option>
      <option name="--unwind">10</option>
      <option name="--xml-ui"/>
    </options>
  </test>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/predicateAnalysisUF.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" hardtimelimit="1000" memlimit="15000" cpuCores="4">
  <option name="-noout"/>
  <option name="-spec">sv-comp</option>
  <option name="-disable-java-assertions"/>
  <option name="-heap">13000M</option>

  <sourcefiles name="BitVectors">
    <includesfile>../programs/benchmarks/BitVectors.set</includesfile>
  </sourcefiles>
  <sourcefiles name="ControlFlowInteger">
    <includesfile>../programs/benchmarks/ControlFlowInteger.set</includesfile>
  </sourcefiles>
  <sourcefiles name="DeviceDrivers64">
    <includesfile>../programs/benchmarks/DeviceDrivers64.set</includesfile>
    <option name="-64"/>
  </sourcefiles>
  <sourcefiles name="HeapManipulation">
    <includesfile>../programs/benchmarks/HeapManipulation.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Loops">
    <includesfile>../programs/benchmarks/Loops.set</includesfile>
  </sourcefiles>
  <sourcefiles name="ProductLines">
    <includesfile>../programs/benchmarks/ProductLines.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Recursive">
    <includesfile>../programs/benchmarks/Recursive.set</includesfile>
  </sourcefiles>
  <sourcefiles name="Sequentialized">
    <includesfile>../programs/benchmarks/Sequentialized.set</includesfile>
    <!-- The following files are expected to have timeouts anyway. -->
    <exclude>../programs/benchmarks/systemc/mem_slave_tlm.3_true.cil.c</exclude>
    <exclude>../programs/benchmarks/systemc/mem_slave_tlm.4_true.cil.c</exclude>
    <exclude>../programs/benchmarks/systemc/mem_slave_tlm.5_true.cil.c</exclude>
    <exclude>../programs/benchmarks/systemc/token_ring.10_true.cil.c</exclude>
    <exclude>../programs/benchmarks/systemc/token_ring.11_true.cil.c</exclude>
    <exclude>../programs/benchmarks/systemc/token_ring.12_true.cil.c</exclude>
    <exclude>../programs/benchmarks/systemc/token_ring.13_true.cil.c</exclude>
  </sourcefiles>
  <sourcefiles name="Simple">
    <includesfile>../programs/benchmarks/Simple.set</includesfile>
    <option name="-setprop">cpa.predicate.handlePointerAliasing=false</option>
  </sourcefiles>

  <rundefinition name="ABElf">
    <option name="-predicateAnalysis-PredAbsRefiner-ABElf-UF" />
  </rundefinition>

  <rundefinition name="ABEl">
    <option name="-predicateAnalysis-PredAbsRefiner-ABEl-UF" />
  </rundefinition>

  <columns>
    <column title="post" numberOfDigits="1">Time for post operator</column>
    <column title="path" numberOfDigits="1">Time for path formula creation</column>
    <column title="precSolving" numberOfDigits="1">Solving time</column>
    <column title="SMTwoInt" numberOfDigits="1">Total time for SMT solver</column>
    <column title="Int" numberOfDigits="1">Interpolant computation</column>
    <column title="refSAT" numberOfDigits="1">Refinement sat check</column>
  </columns>

</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/integration-ldv-unsafes.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" hardtimelimit="1000" memlimit="8000" cpuCores="2">
  <!-- This file contains regression tests from the LDV project.
       It expects the git repository git@bitbucket.org:dbeyer/ldv-benchmarks.git
       to be checked out at test/programs/ldv-benchmarks. -->

  <option name="-setprop">cpa.predicate.mathsat5.furtherOptions=random_seed=42</option>
  <option name="-noout"/>
  <option name="-setprop">statistics.memory=true</option>
  <option name="-heap">7500M</option>
  <option name="-ldv"/>

  <propertyfile>../programs/ldv-benchmarks/PropertyERROR.prp</propertyfile>

  <rundefinition>
    <sourcefiles>
      <include>../programs/ldv-benchmarks/unsafes/*/*/*.c</include>
    </sourcefiles>
  </rundefinition>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/sv-comp.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" memlimit="15000">

  <option name="-noout"/>
  <option name="-spec">test/config/automata/sv-comp.spc</option>
  <option name="-setprop">parser.ignoreCasts=true</option>

  <test name="predicateAnalysis">
    <sourcefiles>
      <includesfile>test/programs/benchmarks/Concurrency.set</includesfile>
      <includesfile>test/programs/benchmarks/ControlFlowInteger.set</includesfile>
      <includesfile>test/programs/benchmarks/DeviceDrivers.set</includesfile>
      <includesfile>test/programs/benchmarks/HeapManipulation.set</includesfile>
      <includesfile>test/programs/benchmarks/SystemC.set</includesfile>
    </sourcefiles>
    <sourcefiles>
      <includesfile>test/programs/benchmarks/DeviceDrivers64.set</includesfile>
      <option name="-setprop">cpa.predicate.machineModel=64-Linux</option>
    </sourcefiles>
    <option name="-predicateAnalysis"/>
    <option name="-heap">12000m</option>
  </test>

  <columns>
    <column title="total">time for CPAchecker</column>
    <column title="cpa time">time for CPA algorithm</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/assumptions/benchmark-restart-with-automaton.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="900" memlimit="12000">
  <test name="lbe-tests">
    <sourcefiles>
      <include>test/programs/nondet_init_programs/systemc/token_ring*.cil.c</include>
      <include>test/programs/nondet_init_programs/systemc/mem_slave_tlm.*.cil.c</include>
      <include>test/programs/nondet_init_programs/systemc/toy.cil.c</include>
    </sourcefiles>
    <option name="-config">test/config/symbpredabsCPA-lbe.properties</option>
    <option name="-setprop">output.disable=true</option>
  </test>
  
  <test name="explicit-tests">
    <sourcefiles>
      <include>test/programs/nondet_init_programs/systemc/token_ring*.cil.c</include>
      <include>test/programs/nondet_init_programs/systemc/mem_slave_tlm.*.cil.c</include>
      <include>test/programs/nondet_init_programs/systemc/toy.cil.c</include>
    </sourcefiles>
    <option name="-config">test/config/explicitAnalysis.properties</option>
    <option name="-setprop">output.disable=true</option>
  </test>

  <test name="restart-with-automaton-tests">
    <sourcefiles>
      <include>test/programs/nondet_init_programs/systemc/token_ring*.cil.c</include>
      <include>test/programs/nondet_init_programs/systemc/mem_slave_tlm.*.cil.c</include>
      <include>test/programs/nondet_init_programs/systemc/toy.cil.c</include>
    </sourcefiles>
    <option name="-config">test/config/restartWithAssumptionAutomaton.properties</option>
    <option name="-setprop">output.disable=true</option>
  </test>
  <columns>
    <column title="total">time for CPAchecker</column>
  </columns>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/parser.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="60" memlimit="1000" cpuCores="1">
  <!-- Test the parser frontend of CPAchecker. -->

  <rundefinition>
    <sourcefiles>
      <includesfile>../programs/benchmarks/BitVectors.set</includesfile>
      <includesfile>../programs/benchmarks/Concurrency.set</includesfile>
      <includesfile>../programs/benchmarks/ControlFlowInteger.set</includesfile>
      <includesfile>../programs/benchmarks/DeviceDrivers64.set</includesfile>
      <includesfile>../programs/benchmarks/DriverChallenges.set</includesfile>
      <includesfile>../programs/benchmarks/HeapManipulation.set</includesfile>
      <includesfile>../programs/benchmarks/Loops.set</includesfile>
      <includesfile>../programs/benchmarks/MemorySafety.set</includesfile>
      <includesfile>../programs/benchmarks/ProductLines.set</includesfile>
      <includesfile>../programs/benchmarks/Recursive.set</includesfile>
      <includesfile>../programs/benchmarks/Sequentialized.set</includesfile>
      <includesfile>../programs/benchmarks/Simple.set</includesfile>
    </sourcefiles>
    <sourcefiles>
      <include>../programs/simple/*.i</include>
      <include>../programs/simple/*/*.i</include>
    </sourcefiles>
    <sourcefiles>
      <include>../programs/simple/*.c</include>
      <include>../programs/simple/*/*.c</include>
      <option name="-preprocess"/>
    </sourcefiles>

    <option name="-heap">500m</option>
    <option name="-noout"/>
    <option name="-generateCFA"/>
  </rundefinition>
</benchmark>

=== mutilin/cpachecker-ldv/test/test-sets/integration-bam-recursive.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cpachecker" timelimit="90" hardtimelimit="100" memlimit="1500" cpuCores="2">

  <resultfiles>**.*</resultfiles>
  <propertyfile>${sourcefile_path}/ALL.prp</propertyfile>

  <option name="-noout"/>
  <option name="-heap">1000M</option>
  
    <sourcefiles name="simple">
      <include>../programs/benchmarks/recursive-simple/*.c</include>
      <option name="-valueAnalysis-bam-rec"/>
    </sourcefiles>
    
    <sourcefiles name="svcomp">
      <includesfile>../programs/benchmarks/Recursive.set</includesfile>
      <option name="-predicateAnalysis-bam-rec-plain"/>
    </sourcefiles>

  <rundefinition name="bam-rec">
  </rundefinition>

</benchmark>
