=== mutilin/cpachecker-ldv/scripts/benchmark/benchmark.dtd
<!DOCTYPE benchmark [

<!ELEMENT benchmark (test*)>
<!ELEMENT test (sourcefiles+,options)>
<!ELEMENT sourcefiles (#PCDATA)>
<!ELEMENT options (option*)>
<!ELEMENT option (#PCDATA)>

<!ATTLIST benchmark tool CDATA #REQUIRED>
<!ATTLIST option name CDATA #REQUIRED>

]>

=== mutilin/cpachecker-ldv/scripts/benchmark/benchmark-allSimpleFiles-cbmc.xml
<?xml version="1.0"?>
<!DOCTYPE benchmark SYSTEM "benchmark.dtd">
<benchmark tool="cbmc">
  <test>
    <sourcefiles>
      <include>test/programs/simple/b*.cil.c</include>
    </sourcefiles>
    <options>
      <option name="--32"/>
      <option name="--error-label">ERROR</option>
      <option name="--unwind">100</option>
    </options>
  </test>
</benchmark>
